### GET request with all params set
GET http://localhost:8080/api/restaurants?searchQuery=pizza&latitude=51.5074&longitude=-0.1278&radiusMeters=200&minPlaceRating=4&desiredPriceLevels=PRICE_LEVEL_INEXPENSIVE&desiredPriceLevels=PRICE_LEVEL_MODERATE&requireOpenNow=true&rankPreference=RELEVANCE

### POST request to search restaurants
POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "searchQuery": "sports bar",
  "latitude": 51.509865,
  "longitude": -0.118092,
  "radiusMeters": 500.0,
  "minPlaceRating": 4.0,
  "desiredPriceLevels": ["PRICE_LEVEL_INEXPENSIVE", "PRICE_LEVEL_MODERATE"],
  "requireOpenNow": true,
  "rankPreference": "RELEVANCE"
}

### GET request to get a particular restaurant by id
GET http://localhost:8080/api/restaurants/ChIJFZfF1coEdkgRpiMmoPwtmCA